name: release

on:
  push:
    branches:
      - main
    paths:
      - "bind/**"
      - "cmd/**"
      - "internal/**"
      - "pkg/**"
      - "ui/**"
      - ".github/workflows/release.yml"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_release.outputs.tag_name }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
