name: test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '_docs/**'
      - '_examples/**'
      - 'README*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '_docs/**'
      - '_examples/**'
      - 'README*.md'

jobs:
#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/setup-go@v2
#        with:
#          go-version: '^1.18'
#      - uses: actions/checkout@v2
#      - name: Lint Go Code
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
#          go get -u golang.org/x/lint/golint
#          golint -set_exit_status ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
          cache: true
      - uses: actions/checkout@v3
      - name: Run Unit tests.
        run: go test ./... -v -covermode=count -coverprofile=coverage.txt
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          fail_ci_if_error: true
  build:
    name: Build
    runs-on: ubuntu-latest
#    needs: [lint, test]
    needs: [test]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
          cache: true
      - uses: actions/checkout@v2
      - name: Build
        run: go build github.com/monkeyWie/gopeed/cmd/gopeed